### 关键参数
per_device_train_batch_size: 2 
gradient_accumulation_steps: 1 # 梯度累积步数
ppo_buffer_size: 8
ppo_epochs: 1 
learning_rate: 1.0e-6
projector_lr: 1.0e-5
num_train_epochs: 1
ppo_score_norm: true # 此参数同时控制 reward 的 scale 和 norm
model_name_or_path: models/qwen2.5-7b-instruct

logging_steps: 1
save_steps: 20
warmup_steps: 0
max_new_tokens: 200
temperature: 0.7

## 多模态相关
freeze_multi_modal_projector: false # 是否冻结多模态投影层

## debug
print_param_status: false # 打印参数状态

### model
reward_model: http
reward_model_type: api
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all

### dataset
template: qwen
cutoff_len: 8192 # 避免长输入被截断
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
plot_loss: true
overwrite_output_dir: true

### train
lr_scheduler_type: cosine
# warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
top_k: 30
top_p: 1.0

# not used
dataset: dataset_mm