from .schema import Column, DatabaseSchema, TableSchema


accidents_schema = DatabaseSchema(
    "accidents",
    table_count=3,
    tables=[
        TableSchema(
            "nesreca",
            [
                Column(name="cas_nesreca", typ="character varying"),
                Column(name="id_nesreca", typ="character"),
                Column(name="kategorija_cesta", typ="character"),
                Column(name="klas_nesreca", typ="character"),
                Column(name="naselje_ali_izven", typ="character"),
                Column(name="opis_prizorisce", typ="character"),
                Column(name="oznaka_cesta_ali_naselje", typ="character"),
                Column(name="oznaka_odsek_ali_ulica", typ="character"),
                Column(name="stacionazna_ali_hisna_st", typ="character varying"),
                Column(name="stanje_povrsina_vozisce", typ="character"),
                Column(name="stanje_promet", typ="character"),
                Column(name="stanje_vozisce", typ="character"),
                Column(name="tekst_cesta_ali_naselje", typ="character varying"),
                Column(name="tekst_odsek_ali_ulica", typ="character varying"),
                Column(name="tip_nesreca", typ="character"),
                Column(name="upravna_enota", typ="integer"),
                Column(name="vreme_nesreca", typ="character"),
                Column(name="vzrok_nesreca", typ="character"),
                Column(name="x", typ="integer"),
                Column(name="x_wgs84", typ="double precision"),
                Column(name="y", typ="integer"),
                Column(name="y_wgs84", typ="double precision"),
            ],
            primary_key="id_nesreca",
        ),
        TableSchema(
            "oseba",
            [
                Column(name="alkotest", typ="numeric"),
                Column(name="alkotest_d", typ="character"),
                Column(name="drzavljanstvo", typ="character"),
                Column(name="id_nesreca", typ="character"),
                Column(name="poskodba", typ="character"),
                Column(name="povzrocitelj_ali_udelezenec", typ="character"),
                Column(name="spol", typ="character"),
                Column(name="starost", typ="integer"),
                Column(name="starost_d", typ="character"),
                Column(name="strokovni_pregled", typ="numeric"),
                Column(name="strokovni_pregled_d", typ="character"),
                Column(name="upravna_enota", typ="integer"),
                Column(name="varnostni_pas_ali_celada", typ="character"),
                Column(name="vozniski_staz_d", typ="character"),
                Column(name="vozniski_staz_ll", typ="integer"),
                Column(name="vozniski_staz_mm", typ="integer"),
                Column(name="vrsta_udelezenca", typ="character"),
            ],
        ),
        TableSchema(
            "upravna_enota",
            [
                Column(name="id_upravna_enota", typ="integer"),
                Column(name="ime_upravna_enota", typ="character varying"),
                Column(name="povrsina", typ="integer"),
                Column(name="st_prebivalcev", typ="integer"),
            ],
            primary_key="id_upravna_enota",
        ),
    ],
    index_count=2,
    indexes=[],
)
