from .schema import Column, DatabaseSchema, TableSchema, add_table_stats


airline_schema = DatabaseSchema(
    "airline",
    table_count=19,
    tables=[
        TableSchema(
            "l_airline_id",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_airport",
            [
                Column(name="code", typ="character"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_airport_id",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_airport_seq_id",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_cancellation",
            [
                Column(name="code", typ="character"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_city_market_id",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_deparrblk",
            [
                Column(name="code", typ="character"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_distance_group_250",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_diversions",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_months",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_ontime_delay_groups",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_quarters",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_state_abr_aviation",
            [
                Column(name="code", typ="character"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_state_fips",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_unique_carriers",
            [
                Column(name="code", typ="character varying"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_weekdays",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_world_area_codes",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "l_yesno_resp",
            [
                Column(name="code", typ="integer"),
                Column(name="description", typ="character varying"),
            ],
            primary_key="code",
        ),
        TableSchema(
            "on_time_on_time_performance_2016_1",
            [
                Column(name="actualelapsedtime", typ="double precision"),
                Column(name="airlineid", typ="integer"),
                Column(name="airtime", typ="double precision"),
                Column(name="arrdel15", typ="integer"),
                Column(name="arrdelay", typ="numeric"),
                Column(name="arrdelayminutes", typ="double precision"),
                Column(name="arrivaldelaygroups", typ="integer"),
                Column(name="arrtime", typ="integer"),
                Column(name="arrtimeblk", typ="character"),
                Column(name="cancellationcode", typ="character"),
                Column(name="cancelled", typ="integer"),
                Column(name="carrier", typ="character"),
                Column(name="carrierdelay", typ="numeric"),
                Column(name="crsarrtime", typ="integer"),
                Column(name="crsdeptime", typ="integer"),
                Column(name="crselapsedtime", typ="double precision"),
                Column(name="dayofmonth", typ="integer"),
                Column(name="dayofweek", typ="integer"),
                Column(name="departuredelaygroups", typ="integer"),
                Column(name="depdel15", typ="integer"),
                Column(name="depdelay", typ="numeric"),
                Column(name="depdelayminutes", typ="double precision"),
                Column(name="deptime", typ="integer"),
                Column(name="deptimeblk", typ="character"),
                Column(name="dest", typ="character"),
                Column(name="destairportid", typ="integer"),
                Column(name="destairportseqid", typ="integer"),
                Column(name="destcitymarketid", typ="integer"),
                Column(name="destcityname", typ="character varying"),
                Column(name="deststate", typ="character"),
                Column(name="deststatefips", typ="integer"),
                Column(name="deststatename", typ="character varying"),
                Column(name="destwac", typ="integer"),
                Column(name="distance", typ="double precision"),
                Column(name="distancegroup", typ="integer"),
                Column(name="div1airport", typ="character"),
                Column(name="div1airportid", typ="integer"),
                Column(name="div1airportseqid", typ="integer"),
                Column(name="div1longestgtime", typ="numeric"),
                Column(name="div1tailnum", typ="character varying"),
                Column(name="div1totalgtime", typ="numeric"),
                Column(name="div1wheelsoff", typ="numeric"),
                Column(name="div1wheelson", typ="numeric"),
                Column(name="div2airport", typ="character"),
                Column(name="div2airportid", typ="integer"),
                Column(name="div2airportseqid", typ="integer"),
                Column(name="div2longestgtime", typ="numeric"),
                Column(name="div2totalgtime", typ="numeric"),
                Column(name="div2wheelson", typ="numeric"),
                Column(name="divactualelapsedtime", typ="numeric"),
                Column(name="divairportlandings", typ="integer"),
                Column(name="divarrdelay", typ="numeric"),
                Column(name="divdistance", typ="numeric"),
                Column(name="diverted", typ="integer"),
                Column(name="divreacheddest", typ="numeric"),
                Column(name="firstdeptime", typ="numeric"),
                Column(name="flightdate", typ="date"),
                Column(name="flightnum", typ="integer"),
                Column(name="flights", typ="double precision"),
                Column(name="lateaircraftdelay", typ="numeric"),
                Column(name="longestaddgtime", typ="numeric"),
                Column(name="month", typ="integer"),
                Column(name="nasdelay", typ="numeric"),
                Column(name="origin", typ="character"),
                Column(name="originairportid", typ="integer"),
                Column(name="originairportseqid", typ="integer"),
                Column(name="origincitymarketid", typ="integer"),
                Column(name="origincityname", typ="character varying"),
                Column(name="originstate", typ="character"),
                Column(name="originstatefips", typ="integer"),
                Column(name="originstatename", typ="character varying"),
                Column(name="originwac", typ="integer"),
                Column(name="quarter", typ="integer"),
                Column(name="securitydelay", typ="numeric"),
                Column(name="tailnum", typ="character varying"),
                Column(name="taxiin", typ="double precision"),
                Column(name="taxiout", typ="double precision"),
                Column(name="totaladdgtime", typ="numeric"),
                Column(name="uniquecarrier", typ="character varying"),
                Column(name="weatherdelay", typ="numeric"),
                Column(name="wheelsoff", typ="integer"),
                Column(name="wheelson", typ="integer"),
                Column(name="year", typ="integer"),
            ],
        ),
    ],
    index_count=18,
    indexes=[
        # Index("l_airline_id", ["code"]),
        # Index("l_airport", ["code"]),
        # Index("l_airport_id", ["code"]),
        # Index("l_airport_seq_id", ["code"]),
        # Index("l_cancellation", ["code"]),
        # Index("l_city_market_id", ["code"]),
        # Index("l_deparrblk", ["code"]),
        # Index("l_distance_group_250", ["code"]),
        # Index("l_diversions", ["code"]),
        # Index("l_months", ["code"]),
        # Index("l_ontime_delay_groups", ["code"]),
        # Index("l_quarters", ["code"]),
        # Index("l_state_abr_aviation", ["code"]),
        # Index("l_state_fips", ["code"]),
        # Index("l_unique_carriers", ["code"]),
        # Index("l_weekdays", ["code"]),
        # Index("l_world_area_codes", ["code"]),
        # Index("l_yesno_resp", ["code"]),
        # Index("on_time_on_time_performance_2016_1", ["airlineid"]),
        # Index("on_time_on_time_performance_2016_1", ["arrivaldelaygroups"]),
        # Index("on_time_on_time_performance_2016_1", ["dayofweek"]),
        # Index("on_time_on_time_performance_2016_1", ["departuredelaygroups"]),
        # Index("on_time_on_time_performance_2016_1", ["destairportid"]),
        # Index("on_time_on_time_performance_2016_1", ["destairportseqid"]),
        # Index("on_time_on_time_performance_2016_1", ["destcitymarketid"]),
        # Index("on_time_on_time_performance_2016_1", ["deststatefips"]),
        # Index("on_time_on_time_performance_2016_1", ["destwac"]),
        # Index("on_time_on_time_performance_2016_1", ["distancegroup"]),
        # Index("on_time_on_time_performance_2016_1", ["div1airportid"]),
        # Index("on_time_on_time_performance_2016_1", ["div1airportseqid"]),
        # Index("on_time_on_time_performance_2016_1", ["div2airportid"]),
        # Index("on_time_on_time_performance_2016_1", ["div2airportseqid"]),
        # Index("on_time_on_time_performance_2016_1", ["diverted"]),
        # Index("on_time_on_time_performance_2016_1", ["month"]),
        # Index("on_time_on_time_performance_2016_1", ["originairportid"]),
        # Index("on_time_on_time_performance_2016_1", ["originairportseqid"]),
        # Index("on_time_on_time_performance_2016_1", ["origincitymarketid"]),
        # Index("on_time_on_time_performance_2016_1", ["originstatefips"]),
        # Index("on_time_on_time_performance_2016_1", ["originwac"]),
        # Index("on_time_on_time_performance_2016_1", ["quarter"]),
        # Index("on_time_on_time_performance_2016_1", ["year"]),
    ],
)
add_table_stats(
    airline_schema,
    "l_airline_id",
    1610,
    {"code": 1610, "description": 1610},
)
add_table_stats(
    airline_schema,
    "l_airport",
    6385,
    {"code": 6385, "description": 6342},
)
add_table_stats(
    airline_schema,
    "l_airport_id",
    6370,
    {"code": 6370, "description": 6351},
)
add_table_stats(
    airline_schema,
    "l_airport_seq_id",
    13295,
    {"code": 13295, "description": 7876},
)
add_table_stats(
    airline_schema,
    "l_cancellation",
    4,
    {"code": 4, "description": 4},
)
add_table_stats(
    airline_schema,
    "l_city_market_id",
    5762,
    {"code": 5762, "description": 5762},
)
add_table_stats(
    airline_schema,
    "l_deparrblk",
    19,
    {"code": 19, "description": 19},
)
add_table_stats(
    airline_schema,
    "l_distance_group_250",
    11,
    {"code": 11, "description": 11},
)
add_table_stats(
    airline_schema,
    "l_diversions",
    7,
    {"code": 7, "description": 7},
)
add_table_stats(
    airline_schema,
    "l_months",
    12,
    {"code": 12, "description": 12},
)
add_table_stats(
    airline_schema,
    "l_ontime_delay_groups",
    15,
    {"code": 15, "description": 15},
)
add_table_stats(
    airline_schema,
    "l_quarters",
    4,
    {"code": 4, "description": 4},
)
add_table_stats(
    airline_schema,
    "l_state_abr_aviation",
    67,
    {"code": 67, "description": 67},
)
add_table_stats(
    airline_schema,
    "l_state_fips",
    74,
    {"code": 74, "description": 73},
)
add_table_stats(
    airline_schema,
    "l_unique_carriers",
    1610,
    {"code": 1610, "description": 1610},
)
add_table_stats(
    airline_schema,
    "l_weekdays",
    8,
    {"code": 8, "description": 8},
)
add_table_stats(
    airline_schema,
    "l_world_area_codes",
    333,
    {"code": 333, "description": 329},
)
add_table_stats(
    airline_schema,
    "l_yesno_resp",
    2,
    {"code": 2, "description": 2},
)
add_table_stats(
    airline_schema,
    "on_time_on_time_performance_2016_1",
    11374666,
    {
        "div2totalgtime": 67,
        "actualelapsedtime": 715,
        "uniquecarrier": 17,
        "crsdeptime": 1394,
        "flightdate": 670,
        "carrier": 17,
        "originstatename": 52,
        "originstatefips": 52,
        "month": 12,
        "year": 2,
        "div2longestgtime": 64,
        "dayofweek": 7,
        "destcitymarketid": 341,
        "departuredelaygroups": 15,
        "arrdelayminutes": 1612,
        "deptimeblk": 19,
        "taxiin": 237,
        "flights": 1,
        "distance": 1612,
        "divarrdelay": 1295,
        "firstdeptime": 1322,
        "taxiout": 188,
        "deststate": 52,
        "originwac": 52,
        "diverted": 2,
        "div1wheelsoff": 1357,
        "cancellationcode": 4,
        "divdistance": 609,
        "carrierdelay": 1530,
        "airtime": 692,
        "destairportid": 367,
        "div1airportid": 346,
        "divairportlandings": 5,
        "div2airport": 81,
        "longestaddgtime": 235,
        "div2airportseqid": 87,
        "div1wheelson": 1374,
        "div2wheelson": 204,
        "depdel15": 2,
        "flightnum": 7195,
        "deststatefips": 52,
        "lateaircraftdelay": 1143,
        "divreacheddest": 2,
        "airlineid": 17,
        "originstate": 52,
        "destwac": 52,
        "distancegroup": 11,
        "wheelson": 1440,
        "deststatename": 52,
        "cancelled": 2,
        "originairportseqid": 404,
        "tailnum": 6055,
        "deptime": 1440,
        "wheelsoff": 1440,
        "destcityname": 360,
        "destairportseqid": 404,
        "div2airportid": 84,
        "crsarrtime": 1436,
        "origin": 367,
        "origincityname": 360,
        "totaladdgtime": 261,
        "securitydelay": 237,
        "arrdel15": 2,
        "originairportid": 367,
        "crselapsedtime": 610,
        "div1tailnum": 5223,
        "quarter": 4,
        "weatherdelay": 1128,
        "div1longestgtime": 201,
        "dest": 367,
        "arrivaldelaygroups": 15,
        "depdelay": 1708,
        "div1airportseqid": 370,
        "arrdelay": 1717,
        "arrtime": 1440,
        "dayofmonth": 31,
        "depdelayminutes": 1621,
        "nasdelay": 1082,
        "origincitymarketid": 341,
        "div1airport": 346,
        "divactualelapsedtime": 1306,
        "div1totalgtime": 260,
        "arrtimeblk": 19,
    },
)
