from .schema import Column, DatabaseSchema, TableSchema


basketball_schema = DatabaseSchema(
    "basketball",
    table_count=9,
    tables=[
        TableSchema(
            "awards_coaches",
            [
                Column(name="award", typ="character varying"),
                Column(name="coachid", typ="integer"),
                Column(name="id", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="note", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
            primary_key="id",
        ),
        TableSchema(
            "awards_players",
            [
                Column(name="award", typ="character varying"),
                Column(name="lgid", typ="character varying"),
                Column(name="note", typ="character varying"),
                Column(name="playerid", typ="integer"),
                Column(name="pos", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
            primary_key=["playerid", "year", "award"],
        ),
        TableSchema(
            "coaches",
            [
                Column(name="coachid", typ="character varying"),
                Column(name="id", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="lost", typ="integer"),
                Column(name="post_losses", typ="integer"),
                Column(name="post_wins", typ="integer"),
                Column(name="stint", typ="integer"),
                Column(name="tmid", typ="integer"),
                Column(name="won", typ="integer"),
                Column(name="year", typ="integer"),
            ],
            primary_key=["id", "year", "tmid", "stint"],
        ),
        TableSchema(
            "draft",
            [
                Column(name="draftfrom", typ="character varying"),
                Column(name="draftoverall", typ="integer"),
                Column(name="draftround", typ="integer"),
                Column(name="draftselection", typ="integer"),
                Column(name="draftyear", typ="integer"),
                Column(name="firstname", typ="character varying"),
                Column(name="id", typ="integer"),
                Column(name="lastname", typ="character varying"),
                Column(name="lgid", typ="character varying"),
                Column(name="playerid", typ="integer"),
                Column(name="suffixname", typ="character varying"),
                Column(name="tmid", typ="integer"),
            ],
            primary_key="id",
        ),
        TableSchema(
            "player_allstar",
            [
                Column(name="assists", typ="integer"),
                Column(name="blocks", typ="integer"),
                Column(name="conference", typ="character varying"),
                Column(name="d_rebounds", typ="integer"),
                Column(name="fg_attempted", typ="integer"),
                Column(name="fg_made", typ="integer"),
                Column(name="first_name", typ="character varying"),
                Column(name="ft_attempted", typ="integer"),
                Column(name="ft_made", typ="integer"),
                Column(name="games_played", typ="integer"),
                Column(name="last_name", typ="character varying"),
                Column(name="league_id", typ="character varying"),
                Column(name="minutes", typ="integer"),
                Column(name="o_rebounds", typ="integer"),
                Column(name="personal_fouls", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="points", typ="integer"),
                Column(name="rebounds", typ="integer"),
                Column(name="season_id", typ="integer"),
                Column(name="steals", typ="integer"),
                Column(name="three_attempted", typ="integer"),
                Column(name="three_made", typ="integer"),
                Column(name="turnovers", typ="integer"),
            ],
            primary_key=["playerid", "season_id"],
        ),
        TableSchema(
            "players",
            [
                Column(name="birthcity", typ="character varying"),
                Column(name="birthcountry", typ="character varying"),
                Column(name="birthdate", typ="character varying"),
                Column(name="birthstate", typ="character varying"),
                Column(name="college", typ="character varying"),
                Column(name="collegeother", typ="character varying"),
                Column(name="deathdate", typ="character varying"),
                Column(name="firstname", typ="character varying"),
                Column(name="firstseason", typ="integer"),
                Column(name="fullgivenname", typ="character varying"),
                Column(name="height", typ="double precision"),
                Column(name="highschool", typ="character varying"),
                Column(name="hscity", typ="character varying"),
                Column(name="hscountry", typ="character varying"),
                Column(name="hsstate", typ="character varying"),
                Column(name="id", typ="integer"),
                Column(name="lastname", typ="character varying"),
                Column(name="lastseason", typ="integer"),
                Column(name="middlename", typ="character varying"),
                Column(name="namegiven", typ="character varying"),
                Column(name="namenick", typ="character varying"),
                Column(name="namesuffix", typ="character varying"),
                Column(name="playerid", typ="character varying"),
                Column(name="pos", typ="character varying"),
                Column(name="race", typ="character varying"),
                Column(name="usefirst", typ="character varying"),
                Column(name="weight", typ="integer"),
            ],
            primary_key="id",
        ),
        TableSchema(
            "players_teams",
            [
                Column(name="assists", typ="integer"),
                Column(name="blocks", typ="integer"),
                Column(name="drebounds", typ="integer"),
                Column(name="fgattempted", typ="integer"),
                Column(name="fgmade", typ="integer"),
                Column(name="ftattempted", typ="integer"),
                Column(name="ftmade", typ="integer"),
                Column(name="gp", typ="integer"),
                Column(name="gs", typ="integer"),
                Column(name="id", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="minutes", typ="integer"),
                Column(name="note", typ="character varying"),
                Column(name="orebounds", typ="integer"),
                Column(name="pf", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="points", typ="integer"),
                Column(name="postassists", typ="integer"),
                Column(name="postblocks", typ="integer"),
                Column(name="postdrebounds", typ="integer"),
                Column(name="postfgattempted", typ="integer"),
                Column(name="postfgmade", typ="integer"),
                Column(name="postftattempted", typ="integer"),
                Column(name="postftmade", typ="integer"),
                Column(name="postgp", typ="integer"),
                Column(name="postgs", typ="integer"),
                Column(name="postminutes", typ="integer"),
                Column(name="postorebounds", typ="integer"),
                Column(name="postpf", typ="integer"),
                Column(name="postpoints", typ="integer"),
                Column(name="postrebounds", typ="integer"),
                Column(name="poststeals", typ="integer"),
                Column(name="postthreeattempted", typ="integer"),
                Column(name="postthreemade", typ="integer"),
                Column(name="postturnovers", typ="integer"),
                Column(name="rebounds", typ="integer"),
                Column(name="steals", typ="integer"),
                Column(name="stint", typ="integer"),
                Column(name="threeattempted", typ="integer"),
                Column(name="threemade", typ="integer"),
                Column(name="tmid", typ="integer"),
                Column(name="turnovers", typ="integer"),
                Column(name="year", typ="integer"),
            ],
            primary_key="id",
        ),
        TableSchema(
            "series_post",
            [
                Column(name="id", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgidloser", typ="character varying"),
                Column(name="lgidwinner", typ="character varying"),
                Column(name="round", typ="character varying"),
                Column(name="series", typ="character varying"),
                Column(name="tmidloser", typ="integer"),
                Column(name="tmidwinner", typ="integer"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
            ],
            primary_key="id",
        ),
        TableSchema(
            "teams",
            [
                Column(name="arena", typ="character varying"),
                Column(name="attendance", typ="integer"),
                Column(name="awaylost", typ="integer"),
                Column(name="awaywon", typ="integer"),
                Column(name="bbtmid", typ="character varying"),
                Column(name="confid", typ="character varying"),
                Column(name="confloss", typ="integer"),
                Column(name="confrank", typ="integer"),
                Column(name="confwon", typ="integer"),
                Column(name="d_3pa", typ="integer"),
                Column(name="d_3pm", typ="integer"),
                Column(name="d_asts", typ="integer"),
                Column(name="d_blk", typ="integer"),
                Column(name="d_dreb", typ="integer"),
                Column(name="d_fga", typ="integer"),
                Column(name="d_fgm", typ="integer"),
                Column(name="d_fta", typ="integer"),
                Column(name="d_ftm", typ="integer"),
                Column(name="d_oreb", typ="integer"),
                Column(name="d_pf", typ="integer"),
                Column(name="d_pts", typ="integer"),
                Column(name="d_reb", typ="integer"),
                Column(name="d_stl", typ="integer"),
                Column(name="d_tmrebound", typ="integer"),
                Column(name="d_to", typ="integer"),
                Column(name="divid", typ="character varying"),
                Column(name="divloss", typ="integer"),
                Column(name="divwon", typ="integer"),
                Column(name="franchid", typ="character varying"),
                Column(name="games", typ="integer"),
                Column(name="homelost", typ="integer"),
                Column(name="homewon", typ="integer"),
                Column(name="id", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="lost", typ="integer"),
                Column(name="min", typ="integer"),
                Column(name="name", typ="character varying"),
                Column(name="neutloss", typ="integer"),
                Column(name="neutwon", typ="integer"),
                Column(name="o_3pa", typ="integer"),
                Column(name="o_3pm", typ="integer"),
                Column(name="o_asts", typ="integer"),
                Column(name="o_blk", typ="integer"),
                Column(name="o_dreb", typ="integer"),
                Column(name="o_fga", typ="integer"),
                Column(name="o_fgm", typ="integer"),
                Column(name="o_fta", typ="integer"),
                Column(name="o_ftm", typ="integer"),
                Column(name="o_oreb", typ="integer"),
                Column(name="o_pf", typ="integer"),
                Column(name="o_pts", typ="integer"),
                Column(name="o_reb", typ="integer"),
                Column(name="o_stl", typ="integer"),
                Column(name="o_tmrebound", typ="integer"),
                Column(name="o_to", typ="integer"),
                Column(name="pace", typ="integer"),
                Column(name="playoff", typ="character varying"),
                Column(name="rank", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="won", typ="integer"),
                Column(name="year", typ="integer"),
            ],
            primary_key=["year", "id"],
        ),
    ],
    index_count=9,
    indexes=[],
)
