from .schema import Column, DatabaseSchema, TableSchema, add_table_stats


chembl_schema = DatabaseSchema(
    "chembl",
    table_count=16,
    tables=[
        TableSchema(
            "activities",
            [
                Column(name="activity_comment", typ="character varying"),
                Column(name="activity_id", typ="integer"),
                Column(name="assay_id", typ="integer"),
                Column(name="doc_id", typ="integer"),
                Column(name="molregno", typ="integer"),
                Column(name="published_activity_type", typ="character varying"),
                Column(name="published_units", typ="character varying"),
                Column(name="published_value", typ="double precision"),
                Column(name="record_id", typ="integer"),
                Column(name="relation", typ="character varying"),
                Column(name="standard_flag", typ="integer"),
                Column(name="standard_type", typ="character varying"),
                Column(name="standard_units", typ="character varying"),
                Column(name="standard_value", typ="double precision"),
            ],
            primary_key="activity_id",
        ),
        TableSchema(
            "assay2target",
            [
                Column(name="assay_id", typ="integer"),
                Column(name="assay_organism", typ="character varying"),
                Column(name="assay_strain", typ="character varying"),
                Column(name="assay_tax_id", typ="integer"),
                Column(name="complex", typ="integer"),
                Column(name="confidence", typ="integer"),
                Column(name="multi", typ="integer"),
                Column(name="relationship_type", typ="character"),
                Column(name="tid", typ="integer"),
            ],
            primary_key=["assay_id", "tid"],
        ),
        TableSchema(
            "assay_type",
            [
                Column(name="assay_desc", typ="character varying"),
                Column(name="assay_type", typ="character varying"),
            ],
            primary_key="assay_type",
        ),
        TableSchema(
            "assays",
            [
                Column(name="assay_id", typ="integer"),
                Column(name="assay_type", typ="character varying"),
                Column(name="description", typ="text"),
                Column(name="doc_id", typ="integer"),
            ],
            primary_key="assay_id",
            large_for_index=["description"],
        ),
        TableSchema(
            "compound_properties",
            [
                Column(name="alogp", typ="double precision"),
                Column(name="hba", typ="integer"),
                Column(name="hbd", typ="integer"),
                Column(name="med_chem_friendly", typ="character varying"),
                Column(name="mol_id", typ="integer"),
                Column(name="molregno", typ="integer"),
                Column(name="mw_freebase", typ="double precision"),
                Column(name="num_ro5_violations", typ="integer"),
                Column(name="psa", typ="double precision"),
                Column(name="ro3_pass", typ="character varying"),
                Column(name="rtb", typ="integer"),
            ],
            primary_key="molregno",
        ),
        TableSchema(
            "compound_records",
            [
                Column(name="compound_key", typ="character varying"),
                Column(name="compound_name", typ="text"),
                Column(name="doc_id", typ="integer"),
                Column(name="molregno", typ="integer"),
                Column(name="record_id", typ="integer"),
            ],
            primary_key="record_id",
            large_for_index=["compound_name"],
        ),
        TableSchema(
            "compound_synonyms",
            [
                Column(name="molregno", typ="integer"),
                Column(name="synonyms", typ="character varying"),
            ],
            primary_key=["molregno", "synonyms"],
        ),
        TableSchema(
            "compounds",
            [
                Column(name="canonical_smiles", typ="text"),
                Column(name="inchi", typ="text"),
                Column(name="inchi_key", typ="character varying"),
                Column(name="molfile", typ="text"),
                Column(name="molformula", typ="character varying"),
                Column(name="molregno", typ="integer"),
                Column(name="molweight", typ="double precision"),
            ],
            primary_key="molregno",
            large_for_index=["canonical_smiles", "inchi", "molfile"],
        ),
        TableSchema(
            "confidence_lookup",
            [
                Column(name="confidence", typ="integer"),
                Column(name="confidence_summary", typ="character varying"),
                Column(name="description", typ="text"),
            ],
            primary_key="confidence",
            large_for_index=["description"],
        ),
        TableSchema(
            "docs",
            [
                Column(name="doc_id", typ="integer"),
                Column(name="first_page", typ="character varying"),
                Column(name="issue", typ="character varying"),
                Column(name="journal", typ="character varying"),
                Column(name="last_page", typ="character varying"),
                Column(name="pubmed_id", typ="integer"),
                Column(name="volume", typ="character varying"),
                Column(name="year", typ="character varying"),
            ],
            primary_key="doc_id",
        ),
        TableSchema(
            "relationship_type",
            [
                Column(name="relationship_desc", typ="character varying"),
                Column(name="relationship_type", typ="character varying"),
            ],
            primary_key="relationship_type",
        ),
        TableSchema(
            "target_class",
            [
                Column(name="l1", typ="character varying"),
                Column(name="l2", typ="character varying"),
                Column(name="l3", typ="character varying"),
                Column(name="l4", typ="character varying"),
                Column(name="l5", typ="character varying"),
                Column(name="l6", typ="character varying"),
                Column(name="l7", typ="character varying"),
                Column(name="l8", typ="character varying"),
                Column(name="target_classification", typ="character varying"),
                Column(name="tc_id", typ="integer"),
                Column(name="tid", typ="integer"),
            ],
            primary_key="tc_id",
        ),
        TableSchema(
            "target_dictionary",
            [
                Column(name="cell_line", typ="character varying"),
                Column(name="db_source", typ="character varying"),
                Column(name="db_version", typ="character varying"),
                Column(name="description", typ="text"),
                Column(name="ec_number", typ="character varying"),
                Column(name="gene_names", typ="text"),
                Column(name="in_drugstore", typ="integer"),
                Column(name="in_starlite", typ="integer"),
                Column(name="keywords", typ="text"),
                Column(name="organism", typ="character varying"),
                Column(name="pref_name", typ="character varying"),
                Column(name="protein_accession", typ="character varying"),
                Column(name="protein_md5sum", typ="character varying"),
                Column(name="protein_sequence", typ="text"),
                Column(name="strain", typ="character varying"),
                Column(name="synonyms", typ="text"),
                Column(name="target_type", typ="character varying"),
                Column(name="tax_id", typ="integer"),
                Column(name="tid", typ="integer"),
                Column(name="tissue", typ="character varying"),
            ],
            primary_key="tid",
            large_for_index=["description", "gene_names", "keywords", "protein_sequence", "synonyms"],
        ),
        TableSchema(
            "target_protein",
            [
                Column(name="assay_organism", typ="character varying"),
                Column(name="assay_type", typ="character varying"),
                Column(name="canonical_smiles", typ="text"),
                Column(name="organism", typ="character varying"),
                Column(name="protein_accession", typ="character varying"),
                Column(name="relation", typ="character varying"),
                Column(name="relationship_type", typ="character"),
                Column(name="standard_type", typ="character varying"),
                Column(name="standard_units", typ="character varying"),
                Column(name="standard_value", typ="double precision"),
                Column(name="target_type", typ="character varying"),
            ],
            large_for_index=["canonical_smiles"],
        ),
        TableSchema(
            "target_type",
            [
                Column(name="target_desc", typ="character varying"),
                Column(name="target_type", typ="character varying"),
            ],
            primary_key="target_type",
        ),
        TableSchema(
            "version",
            [
                Column(name="comments", typ="text"),
                Column(name="creation_date", typ="date"),
                Column(name="name", typ="character varying"),
            ],
            primary_key="name",
            large_for_index=["comments"],
        ),
    ],
    index_count=15,
    indexes=[],
)
add_table_stats(
    chembl_schema,
    "activities",
    1936969,
    {
        "published_units": 1363,
        "published_value": 35576,
        "relation": 306,
        "activity_id": 1936969,
        "standard_type": 5525,
        "standard_value": 38663,
        "molregno": 438805,
        "activity_comment": 136,
        "assay_id": 329184,
        "standard_flag": 3,
        "published_activity_type": 5487,
        "standard_units": 1353,
        "doc_id": 26297,
        "record_id": 519819,
    },
)
add_table_stats(
    chembl_schema,
    "assay2target",
    384024,
    {
        "confidence": 4,
        "complex": 2,
        "multi": 2,
        "assay_strain": 908,
        "assay_tax_id": 1245,
        "relationship_type": 4,
        "assay_id": 329188,
        "assay_organism": 2412,
        "tid": 5441,
    },
)
add_table_stats(
    chembl_schema,
    "assay_type",
    4,
    {"assay_type": 4, "assay_desc": 4},
)
add_table_stats(
    chembl_schema,
    "assays",
    329250,
    {"assay_id": 329250, "assay_type": 3, "doc_id": 26299, "description": 297633},
)
add_table_stats(
    chembl_schema,
    "compound_properties",
    440055,
    {
        "med_chem_friendly": 2,
        "rtb": 175,
        "psa": 28770,
        "mol_id": 1197,
        "molregno": 440055,
        "mw_freebase": 120613,
        "ro3_pass": 2,
        "num_ro5_violations": 5,
        "hbd": 77,
        "alogp": 20121,
        "hba": 104,
    },
)
add_table_stats(
    chembl_schema,
    "compound_records",
    521237,
    {
        "compound_name": 441900,
        "molregno": 440047,
        "compound_key": 64869,
        "doc_id": 26297,
        "record_id": 521237,
    },
)
add_table_stats(
    chembl_schema,
    "compound_synonyms",
    7541,
    {"molregno": 4328, "synonyms": 6688},
)
add_table_stats(
    chembl_schema,
    "compounds",
    440055,
    {
        "molfile": 440055,
        "canonical_smiles": 439366,
        "molregno": 440055,
        "inchi_key": 438480,
        "molformula": 160654,
        "molweight": 132366,
        "inchi": 438480,
    },
)
add_table_stats(
    chembl_schema,
    "confidence_lookup",
    4,
    {"confidence": 4, "confidence_summary": 4, "description": 4},
)
add_table_stats(
    chembl_schema,
    "docs",
    26299,
    {
        "first_page": 6349,
        "year": 29,
        "volume": 58,
        "issue": 63,
        "journal": 12,
        "pubmed_id": 23771,
        "last_page": 6379,
        "doc_id": 26299,
    },
)
add_table_stats(
    chembl_schema,
    "relationship_type",
    2,
    {"relationship_desc": 2, "relationship_type": 2},
)
add_table_stats(
    chembl_schema,
    "target_class",
    3775,
    {
        "l8": 4,
        "tc_id": 3775,
        "l3": 52,
        "l1": 12,
        "target_classification": 451,
        "l5": 177,
        "l6": 84,
        "l7": 75,
        "l2": 22,
        "tid": 3622,
        "l4": 93,
    },
)
add_table_stats(
    chembl_schema,
    "target_dictionary",
    5694,
    {
        "tax_id": 920,
        "protein_accession": 3614,
        "in_starlite": 2,
        "keywords": 2742,
        "in_drugstore": 1,
        "strain": 0,
        "db_source": 3,
        "db_version": 2,
        "description": 2610,
        "gene_names": 3077,
        "cell_line": 1150,
        "synonyms": 2725,
        "pref_name": 4234,
        "tissue": 138,
        "protein_sequence": 3585,
        "protein_md5sum": 3585,
        "target_type": 7,
        "ec_number": 600,
        "organism": 934,
        "tid": 5694,
    },
)
add_table_stats(
    chembl_schema,
    "target_protein",
    10000,
    {
        "canonical_smiles": 6916,
        "relation": 1,
        "standard_units": 1,
        "standard_type": 2,
        "standard_value": 2127,
        "relationship_type": 2,
        "protein_accession": 9,
        "assay_organism": 26,
        "target_type": 1,
        "organism": 1,
        "assay_type": 2,
    },
)
add_table_stats(
    chembl_schema,
    "target_type",
    8,
    {"target_type": 8, "target_desc": 8},
)
add_table_stats(
    chembl_schema,
    "version",
    1,
    {"creation_date": 1, "comments": 1, "name": 1},
)
