from .schema import Column, DatabaseSchema, TableSchema


credit_schema = DatabaseSchema(
    "credit",
    table_count=8,
    tables=[
        TableSchema(
            "category",
            [
                Column(name="category_code", typ="character"),
                Column(name="category_desc", typ="character varying"),
                Column(name="category_no", typ="integer"),
            ],
            primary_key="category_no",
        ),
        TableSchema(
            "charge",
            [
                Column(name="category_no", typ="integer"),
                Column(name="charge_amt", typ="numeric"),
                Column(name="charge_code", typ="character"),
                Column(name="charge_dt", typ="character varying"),
                Column(name="charge_no", typ="integer"),
                Column(name="member_no", typ="integer"),
                Column(name="provider_no", typ="integer"),
                Column(name="statement_no", typ="integer"),
            ],
            primary_key="charge_no",
        ),
        TableSchema(
            "corporation",
            [
                Column(name="city", typ="character varying"),
                Column(name="corp_code", typ="character"),
                Column(name="corp_name", typ="character varying"),
                Column(name="corp_no", typ="integer"),
                Column(name="country", typ="character"),
                Column(name="expr_dt", typ="character varying"),
                Column(name="mail_code", typ="character"),
                Column(name="phone_no", typ="character"),
                Column(name="region_no", typ="integer"),
                Column(name="state_prov", typ="character"),
                Column(name="street", typ="character varying"),
            ],
            primary_key="corp_no",
        ),
        TableSchema(
            "member",
            [
                Column(name="city", typ="character varying"),
                Column(name="corp_no", typ="integer"),
                Column(name="country", typ="character"),
                Column(name="curr_balance", typ="numeric"),
                Column(name="expr_dt", typ="character varying"),
                Column(name="firstname", typ="character varying"),
                Column(name="issue_dt", typ="character varying"),
                Column(name="lastname", typ="character varying"),
                Column(name="mail_code", typ="character"),
                Column(name="member_code", typ="character"),
                Column(name="member_no", typ="integer"),
                Column(name="middleinitial", typ="character"),
                Column(name="phone_no", typ="character"),
                Column(name="photograph", typ="bytea"),
                Column(name="prev_balance", typ="numeric"),
                Column(name="region_no", typ="integer"),
                Column(name="state_prov", typ="character"),
                Column(name="street", typ="character varying"),
            ],
            primary_key="member_no",
            large_for_index=["photograph"],
        ),
        TableSchema(
            "payment",
            [
                Column(name="member_no", typ="integer"),
                Column(name="payment_amt", typ="numeric"),
                Column(name="payment_code", typ="character"),
                Column(name="payment_dt", typ="character varying"),
                Column(name="payment_no", typ="integer"),
                Column(name="statement_no", typ="integer"),
            ],
            primary_key="payment_no",
        ),
        TableSchema(
            "provider",
            [
                Column(name="city", typ="character varying"),
                Column(name="country", typ="character"),
                Column(name="expr_dt", typ="character varying"),
                Column(name="issue_dt", typ="character varying"),
                Column(name="mail_code", typ="character"),
                Column(name="phone_no", typ="character"),
                Column(name="provider_code", typ="character"),
                Column(name="provider_name", typ="character varying"),
                Column(name="provider_no", typ="integer"),
                Column(name="region_no", typ="integer"),
                Column(name="state_prov", typ="character"),
                Column(name="street", typ="character varying"),
            ],
            primary_key="provider_no",
        ),
        TableSchema(
            "region",
            [
                Column(name="city", typ="character varying"),
                Column(name="country", typ="character"),
                Column(name="mail_code", typ="character"),
                Column(name="phone_no", typ="character"),
                Column(name="region_code", typ="character"),
                Column(name="region_name", typ="character varying"),
                Column(name="region_no", typ="integer"),
                Column(name="state_prov", typ="character"),
                Column(name="street", typ="character varying"),
            ],
            primary_key="region_no",
        ),
        TableSchema(
            "statement",
            [
                Column(name="due_dt", typ="character varying"),
                Column(name="member_no", typ="integer"),
                Column(name="statement_amt", typ="numeric"),
                Column(name="statement_code", typ="character"),
                Column(name="statement_dt", typ="character varying"),
                Column(name="statement_no", typ="integer"),
            ],
            primary_key="statement_no",
        ),
    ],
    index_count=8,
    indexes=[],
)
