from .schema import Column, DatabaseSchema, TableSchema, add_table_stats


dsb_schema = DatabaseSchema(
    "dsb",
    table_count=25,
    tables=[
        TableSchema(
            "call_center",
            [
                Column(name="cc_call_center_id", typ="character"),
                Column(name="cc_call_center_sk", typ="integer"),
                Column(name="cc_city", typ="character varying"),
                Column(name="cc_class", typ="character varying"),
                Column(name="cc_closed_date_sk", typ="integer"),
                Column(name="cc_company", typ="integer"),
                Column(name="cc_company_name", typ="character"),
                Column(name="cc_country", typ="character varying"),
                Column(name="cc_county", typ="character varying"),
                Column(name="cc_division", typ="integer"),
                Column(name="cc_division_name", typ="character varying"),
                Column(name="cc_employees", typ="integer"),
                Column(name="cc_gmt_offset", typ="numeric"),
                Column(name="cc_hours", typ="character"),
                Column(name="cc_manager", typ="character varying"),
                Column(name="cc_market_manager", typ="character varying"),
                Column(name="cc_mkt_class", typ="character"),
                Column(name="cc_mkt_desc", typ="character varying"),
                Column(name="cc_mkt_id", typ="integer"),
                Column(name="cc_name", typ="character varying"),
                Column(name="cc_open_date_sk", typ="integer"),
                Column(name="cc_rec_end_date", typ="date"),
                Column(name="cc_rec_start_date", typ="date"),
                Column(name="cc_sq_ft", typ="integer"),
                Column(name="cc_state", typ="character"),
                Column(name="cc_street_name", typ="character varying"),
                Column(name="cc_street_number", typ="character"),
                Column(name="cc_street_type", typ="character"),
                Column(name="cc_suite_number", typ="character"),
                Column(name="cc_tax_percentage", typ="numeric"),
                Column(name="cc_zip", typ="character"),
            ],
            primary_key="cc_call_center_sk",
        ),
        TableSchema(
            "catalog_page",
            [
                Column(name="cp_catalog_number", typ="integer"),
                Column(name="cp_catalog_page_id", typ="character"),
                Column(name="cp_catalog_page_number", typ="integer"),
                Column(name="cp_catalog_page_sk", typ="integer"),
                Column(name="cp_department", typ="character varying"),
                Column(name="cp_description", typ="character varying"),
                Column(name="cp_end_date_sk", typ="integer"),
                Column(name="cp_start_date_sk", typ="integer"),
                Column(name="cp_type", typ="character varying"),
            ],
            primary_key="cp_catalog_page_sk",
        ),
        TableSchema(
            "catalog_returns",
            [
                Column(name="cr_call_center_sk", typ="integer"),
                Column(name="cr_catalog_page_sk", typ="integer"),
                Column(name="cr_fee", typ="numeric"),
                Column(name="cr_item_sk", typ="integer"),
                Column(name="cr_net_loss", typ="numeric"),
                Column(name="cr_order_number", typ="integer"),
                Column(name="cr_reason_sk", typ="integer"),
                Column(name="cr_refunded_addr_sk", typ="integer"),
                Column(name="cr_refunded_cash", typ="numeric"),
                Column(name="cr_refunded_cdemo_sk", typ="integer"),
                Column(name="cr_refunded_customer_sk", typ="integer"),
                Column(name="cr_refunded_hdemo_sk", typ="integer"),
                Column(name="cr_return_amount", typ="numeric"),
                Column(name="cr_return_amt_inc_tax", typ="numeric"),
                Column(name="cr_return_quantity", typ="integer"),
                Column(name="cr_return_ship_cost", typ="numeric"),
                Column(name="cr_return_tax", typ="numeric"),
                Column(name="cr_returned_date_sk", typ="integer"),
                Column(name="cr_returned_time_sk", typ="integer"),
                Column(name="cr_returning_addr_sk", typ="integer"),
                Column(name="cr_returning_cdemo_sk", typ="integer"),
                Column(name="cr_returning_customer_sk", typ="integer"),
                Column(name="cr_returning_hdemo_sk", typ="integer"),
                Column(name="cr_reversed_charge", typ="numeric"),
                Column(name="cr_ship_mode_sk", typ="integer"),
                Column(name="cr_store_credit", typ="numeric"),
                Column(name="cr_warehouse_sk", typ="integer"),
            ],
            primary_key=["cr_item_sk", "cr_order_number"],
        ),
        TableSchema(
            "catalog_sales",
            [
                Column(name="cs_bill_addr_sk", typ="integer"),
                Column(name="cs_bill_cdemo_sk", typ="integer"),
                Column(name="cs_bill_customer_sk", typ="integer"),
                Column(name="cs_bill_hdemo_sk", typ="integer"),
                Column(name="cs_call_center_sk", typ="integer"),
                Column(name="cs_catalog_page_sk", typ="integer"),
                Column(name="cs_coupon_amt", typ="numeric"),
                Column(name="cs_ext_discount_amt", typ="numeric"),
                Column(name="cs_ext_list_price", typ="numeric"),
                Column(name="cs_ext_sales_price", typ="numeric"),
                Column(name="cs_ext_ship_cost", typ="numeric"),
                Column(name="cs_ext_tax", typ="numeric"),
                Column(name="cs_ext_wholesale_cost", typ="numeric"),
                Column(name="cs_item_sk", typ="integer"),
                Column(name="cs_list_price", typ="numeric"),
                Column(name="cs_net_paid", typ="numeric"),
                Column(name="cs_net_paid_inc_ship", typ="numeric"),
                Column(name="cs_net_paid_inc_ship_tax", typ="numeric"),
                Column(name="cs_net_paid_inc_tax", typ="numeric"),
                Column(name="cs_net_profit", typ="numeric"),
                Column(name="cs_order_number", typ="integer"),
                Column(name="cs_promo_sk", typ="integer"),
                Column(name="cs_quantity", typ="integer"),
                Column(name="cs_sales_price", typ="numeric"),
                Column(name="cs_ship_addr_sk", typ="integer"),
                Column(name="cs_ship_cdemo_sk", typ="integer"),
                Column(name="cs_ship_customer_sk", typ="integer"),
                Column(name="cs_ship_date_sk", typ="integer"),
                Column(name="cs_ship_hdemo_sk", typ="integer"),
                Column(name="cs_ship_mode_sk", typ="integer"),
                Column(name="cs_sold_date_sk", typ="integer"),
                Column(name="cs_sold_time_sk", typ="integer"),
                Column(name="cs_warehouse_sk", typ="integer"),
                Column(name="cs_wholesale_cost", typ="numeric"),
            ],
            primary_key=["cs_item_sk", "cs_order_number"],
        ),
        TableSchema(
            "customer",
            [
                Column(name="c_birth_country", typ="character varying"),
                Column(name="c_birth_day", typ="integer"),
                Column(name="c_birth_month", typ="integer"),
                Column(name="c_birth_year", typ="integer"),
                Column(name="c_current_addr_sk", typ="integer"),
                Column(name="c_current_cdemo_sk", typ="integer"),
                Column(name="c_current_hdemo_sk", typ="integer"),
                Column(name="c_customer_id", typ="character"),
                Column(name="c_customer_sk", typ="integer"),
                Column(name="c_email_address", typ="character"),
                Column(name="c_first_name", typ="character"),
                Column(name="c_first_sales_date_sk", typ="integer"),
                Column(name="c_first_shipto_date_sk", typ="integer"),
                Column(name="c_last_name", typ="character"),
                Column(name="c_last_review_date_sk", typ="integer"),
                Column(name="c_login", typ="character"),
                Column(name="c_preferred_cust_flag", typ="character"),
                Column(name="c_salutation", typ="character"),
            ],
            primary_key="c_customer_sk",
        ),
        TableSchema(
            "customer_address",
            [
                Column(name="ca_address_id", typ="character"),
                Column(name="ca_address_sk", typ="integer"),
                Column(name="ca_city", typ="character varying"),
                Column(name="ca_country", typ="character varying"),
                Column(name="ca_county", typ="character varying"),
                Column(name="ca_gmt_offset", typ="numeric"),
                Column(name="ca_location_type", typ="character"),
                Column(name="ca_state", typ="character"),
                Column(name="ca_street_name", typ="character varying"),
                Column(name="ca_street_number", typ="character"),
                Column(name="ca_street_type", typ="character"),
                Column(name="ca_suite_number", typ="character"),
                Column(name="ca_zip", typ="character"),
            ],
            primary_key="ca_address_sk",
        ),
        TableSchema(
            "customer_demographics",
            [
                Column(name="cd_credit_rating", typ="character"),
                Column(name="cd_demo_sk", typ="integer"),
                Column(name="cd_dep_college_count", typ="integer"),
                Column(name="cd_dep_count", typ="integer"),
                Column(name="cd_dep_employed_count", typ="integer"),
                Column(name="cd_education_status", typ="character"),
                Column(name="cd_gender", typ="character"),
                Column(name="cd_marital_status", typ="character"),
                Column(name="cd_purchase_estimate", typ="integer"),
            ],
            primary_key="cd_demo_sk",
        ),
        TableSchema(
            "date_dim",
            [
                Column(name="d_current_day", typ="character"),
                Column(name="d_current_month", typ="character"),
                Column(name="d_current_quarter", typ="character"),
                Column(name="d_current_week", typ="character"),
                Column(name="d_current_year", typ="character"),
                Column(name="d_date", typ="date"),
                Column(name="d_date_id", typ="character"),
                Column(name="d_date_sk", typ="integer"),
                Column(name="d_day_name", typ="character"),
                Column(name="d_dom", typ="integer"),
                Column(name="d_dow", typ="integer"),
                Column(name="d_first_dom", typ="integer"),
                Column(name="d_following_holiday", typ="character"),
                Column(name="d_fy_quarter_seq", typ="integer"),
                Column(name="d_fy_week_seq", typ="integer"),
                Column(name="d_fy_year", typ="integer"),
                Column(name="d_holiday", typ="character"),
                Column(name="d_last_dom", typ="integer"),
                Column(name="d_month_seq", typ="integer"),
                Column(name="d_moy", typ="integer"),
                Column(name="d_qoy", typ="integer"),
                Column(name="d_quarter_name", typ="character"),
                Column(name="d_quarter_seq", typ="integer"),
                Column(name="d_same_day_lq", typ="integer"),
                Column(name="d_same_day_ly", typ="integer"),
                Column(name="d_week_seq", typ="integer"),
                Column(name="d_weekend", typ="character"),
                Column(name="d_year", typ="integer"),
            ],
            primary_key="d_date_sk",
        ),
        TableSchema(
            "dbgen_version",
            [
                Column(name="dv_cmdline_args", typ="character varying"),
                Column(name="dv_create_date", typ="date"),
                Column(name="dv_create_time", typ="time without time zone"),
                Column(name="dv_version", typ="character varying"),
            ],
        ),
        TableSchema(
            "household_demographics",
            [
                Column(name="hd_buy_potential", typ="character"),
                Column(name="hd_demo_sk", typ="integer"),
                Column(name="hd_dep_count", typ="integer"),
                Column(name="hd_income_band_sk", typ="integer"),
                Column(name="hd_vehicle_count", typ="integer"),
            ],
            primary_key="hd_demo_sk",
        ),
        TableSchema(
            "income_band",
            [
                Column(name="ib_income_band_sk", typ="integer"),
                Column(name="ib_lower_bound", typ="integer"),
                Column(name="ib_upper_bound", typ="integer"),
            ],
            primary_key="ib_income_band_sk",
        ),
        TableSchema(
            "inventory",
            [
                Column(name="inv_date_sk", typ="integer"),
                Column(name="inv_item_sk", typ="integer"),
                Column(name="inv_quantity_on_hand", typ="integer"),
                Column(name="inv_warehouse_sk", typ="integer"),
            ],
            primary_key=["inv_date_sk", "inv_item_sk", "inv_warehouse_sk"],
        ),
        TableSchema(
            "item",
            [
                Column(name="i_brand", typ="character"),
                Column(name="i_brand_id", typ="integer"),
                Column(name="i_category", typ="character"),
                Column(name="i_category_id", typ="integer"),
                Column(name="i_class", typ="character"),
                Column(name="i_class_id", typ="integer"),
                Column(name="i_color", typ="character"),
                Column(name="i_container", typ="character"),
                Column(name="i_current_price", typ="numeric"),
                Column(name="i_formulation", typ="character"),
                Column(name="i_item_desc", typ="character varying"),
                Column(name="i_item_id", typ="character"),
                Column(name="i_item_sk", typ="integer"),
                Column(name="i_manager_id", typ="integer"),
                Column(name="i_manufact", typ="character"),
                Column(name="i_manufact_id", typ="integer"),
                Column(name="i_product_name", typ="character"),
                Column(name="i_rec_end_date", typ="date"),
                Column(name="i_rec_start_date", typ="date"),
                Column(name="i_size", typ="character"),
                Column(name="i_units", typ="character"),
                Column(name="i_wholesale_cost", typ="numeric"),
            ],
            primary_key="i_item_sk",
        ),
        TableSchema(
            "promotion",
            [
                Column(name="p_channel_catalog", typ="character"),
                Column(name="p_channel_demo", typ="character"),
                Column(name="p_channel_details", typ="character varying"),
                Column(name="p_channel_dmail", typ="character"),
                Column(name="p_channel_email", typ="character"),
                Column(name="p_channel_event", typ="character"),
                Column(name="p_channel_press", typ="character"),
                Column(name="p_channel_radio", typ="character"),
                Column(name="p_channel_tv", typ="character"),
                Column(name="p_cost", typ="numeric"),
                Column(name="p_discount_active", typ="character"),
                Column(name="p_end_date_sk", typ="integer"),
                Column(name="p_item_sk", typ="integer"),
                Column(name="p_promo_id", typ="character"),
                Column(name="p_promo_name", typ="character"),
                Column(name="p_promo_sk", typ="integer"),
                Column(name="p_purpose", typ="character"),
                Column(name="p_response_target", typ="integer"),
                Column(name="p_start_date_sk", typ="integer"),
            ],
            primary_key="p_promo_sk",
        ),
        TableSchema(
            "reason",
            [
                Column(name="r_reason_desc", typ="character"),
                Column(name="r_reason_id", typ="character"),
                Column(name="r_reason_sk", typ="integer"),
            ],
            primary_key="r_reason_sk",
        ),
        TableSchema(
            "ship_mode",
            [
                Column(name="sm_carrier", typ="character"),
                Column(name="sm_code", typ="character"),
                Column(name="sm_contract", typ="character"),
                Column(name="sm_ship_mode_id", typ="character"),
                Column(name="sm_ship_mode_sk", typ="integer"),
                Column(name="sm_type", typ="character"),
            ],
            primary_key="sm_ship_mode_sk",
        ),
        TableSchema(
            "store",
            [
                Column(name="s_city", typ="character varying"),
                Column(name="s_closed_date_sk", typ="integer"),
                Column(name="s_company_id", typ="integer"),
                Column(name="s_company_name", typ="character varying"),
                Column(name="s_country", typ="character varying"),
                Column(name="s_county", typ="character varying"),
                Column(name="s_division_id", typ="integer"),
                Column(name="s_division_name", typ="character varying"),
                Column(name="s_floor_space", typ="integer"),
                Column(name="s_geography_class", typ="character varying"),
                Column(name="s_gmt_offset", typ="numeric"),
                Column(name="s_hours", typ="character"),
                Column(name="s_manager", typ="character varying"),
                Column(name="s_market_desc", typ="character varying"),
                Column(name="s_market_id", typ="integer"),
                Column(name="s_market_manager", typ="character varying"),
                Column(name="s_number_employees", typ="integer"),
                Column(name="s_rec_end_date", typ="date"),
                Column(name="s_rec_start_date", typ="date"),
                Column(name="s_state", typ="character"),
                Column(name="s_store_id", typ="character"),
                Column(name="s_store_name", typ="character varying"),
                Column(name="s_store_sk", typ="integer"),
                Column(name="s_street_name", typ="character varying"),
                Column(name="s_street_number", typ="character varying"),
                Column(name="s_street_type", typ="character"),
                Column(name="s_suite_number", typ="character"),
                Column(name="s_tax_precentage", typ="numeric"),
                Column(name="s_zip", typ="character"),
            ],
            primary_key="s_store_sk",
        ),
        TableSchema(
            "store_returns",
            [
                Column(name="sr_addr_sk", typ="integer"),
                Column(name="sr_cdemo_sk", typ="integer"),
                Column(name="sr_customer_sk", typ="integer"),
                Column(name="sr_fee", typ="numeric"),
                Column(name="sr_hdemo_sk", typ="integer"),
                Column(name="sr_item_sk", typ="integer"),
                Column(name="sr_net_loss", typ="numeric"),
                Column(name="sr_reason_sk", typ="integer"),
                Column(name="sr_refunded_cash", typ="numeric"),
                Column(name="sr_return_amt", typ="numeric"),
                Column(name="sr_return_amt_inc_tax", typ="numeric"),
                Column(name="sr_return_quantity", typ="integer"),
                Column(name="sr_return_ship_cost", typ="numeric"),
                Column(name="sr_return_tax", typ="numeric"),
                Column(name="sr_return_time_sk", typ="integer"),
                Column(name="sr_returned_date_sk", typ="integer"),
                Column(name="sr_reversed_charge", typ="numeric"),
                Column(name="sr_store_credit", typ="numeric"),
                Column(name="sr_store_sk", typ="integer"),
                Column(name="sr_ticket_number", typ="integer"),
            ],
            primary_key=["sr_item_sk", "sr_ticket_number"],
        ),
        TableSchema(
            "store_sales",
            [
                Column(name="ss_addr_sk", typ="integer"),
                Column(name="ss_cdemo_sk", typ="integer"),
                Column(name="ss_coupon_amt", typ="numeric"),
                Column(name="ss_customer_sk", typ="integer"),
                Column(name="ss_ext_discount_amt", typ="numeric"),
                Column(name="ss_ext_list_price", typ="numeric"),
                Column(name="ss_ext_sales_price", typ="numeric"),
                Column(name="ss_ext_tax", typ="numeric"),
                Column(name="ss_ext_wholesale_cost", typ="numeric"),
                Column(name="ss_hdemo_sk", typ="integer"),
                Column(name="ss_item_sk", typ="integer"),
                Column(name="ss_list_price", typ="numeric"),
                Column(name="ss_net_paid", typ="numeric"),
                Column(name="ss_net_paid_inc_tax", typ="numeric"),
                Column(name="ss_net_profit", typ="numeric"),
                Column(name="ss_promo_sk", typ="integer"),
                Column(name="ss_quantity", typ="integer"),
                Column(name="ss_sales_price", typ="numeric"),
                Column(name="ss_sold_date_sk", typ="integer"),
                Column(name="ss_sold_time_sk", typ="integer"),
                Column(name="ss_store_sk", typ="integer"),
                Column(name="ss_ticket_number", typ="integer"),
                Column(name="ss_wholesale_cost", typ="numeric"),
            ],
            primary_key=["ss_item_sk", "ss_ticket_number"],
        ),
        TableSchema(
            "time_dim",
            [
                Column(name="t_am_pm", typ="character"),
                Column(name="t_hour", typ="integer"),
                Column(name="t_meal_time", typ="character"),
                Column(name="t_minute", typ="integer"),
                Column(name="t_second", typ="integer"),
                Column(name="t_shift", typ="character"),
                Column(name="t_sub_shift", typ="character"),
                Column(name="t_time", typ="integer"),
                Column(name="t_time_id", typ="character"),
                Column(name="t_time_sk", typ="integer"),
            ],
            primary_key="t_time_sk",
        ),
        TableSchema(
            "warehouse",
            [
                Column(name="w_city", typ="character varying"),
                Column(name="w_country", typ="character varying"),
                Column(name="w_county", typ="character varying"),
                Column(name="w_gmt_offset", typ="numeric"),
                Column(name="w_state", typ="character"),
                Column(name="w_street_name", typ="character varying"),
                Column(name="w_street_number", typ="character"),
                Column(name="w_street_type", typ="character"),
                Column(name="w_suite_number", typ="character"),
                Column(name="w_warehouse_id", typ="character"),
                Column(name="w_warehouse_name", typ="character varying"),
                Column(name="w_warehouse_sk", typ="integer"),
                Column(name="w_warehouse_sq_ft", typ="integer"),
                Column(name="w_zip", typ="character"),
            ],
            primary_key="w_warehouse_sk",
        ),
        TableSchema(
            "web_page",
            [
                Column(name="wp_access_date_sk", typ="integer"),
                Column(name="wp_autogen_flag", typ="character"),
                Column(name="wp_char_count", typ="integer"),
                Column(name="wp_creation_date_sk", typ="integer"),
                Column(name="wp_customer_sk", typ="integer"),
                Column(name="wp_image_count", typ="integer"),
                Column(name="wp_link_count", typ="integer"),
                Column(name="wp_max_ad_count", typ="integer"),
                Column(name="wp_rec_end_date", typ="date"),
                Column(name="wp_rec_start_date", typ="date"),
                Column(name="wp_type", typ="character"),
                Column(name="wp_url", typ="character varying"),
                Column(name="wp_web_page_id", typ="character"),
                Column(name="wp_web_page_sk", typ="integer"),
            ],
            primary_key="wp_web_page_sk",
        ),
        TableSchema(
            "web_returns",
            [
                Column(name="wr_account_credit", typ="numeric"),
                Column(name="wr_fee", typ="numeric"),
                Column(name="wr_item_sk", typ="integer"),
                Column(name="wr_net_loss", typ="numeric"),
                Column(name="wr_order_number", typ="integer"),
                Column(name="wr_reason_sk", typ="integer"),
                Column(name="wr_refunded_addr_sk", typ="integer"),
                Column(name="wr_refunded_cash", typ="numeric"),
                Column(name="wr_refunded_cdemo_sk", typ="integer"),
                Column(name="wr_refunded_customer_sk", typ="integer"),
                Column(name="wr_refunded_hdemo_sk", typ="integer"),
                Column(name="wr_return_amt", typ="numeric"),
                Column(name="wr_return_amt_inc_tax", typ="numeric"),
                Column(name="wr_return_quantity", typ="integer"),
                Column(name="wr_return_ship_cost", typ="numeric"),
                Column(name="wr_return_tax", typ="numeric"),
                Column(name="wr_returned_date_sk", typ="integer"),
                Column(name="wr_returned_time_sk", typ="integer"),
                Column(name="wr_returning_addr_sk", typ="integer"),
                Column(name="wr_returning_cdemo_sk", typ="integer"),
                Column(name="wr_returning_customer_sk", typ="integer"),
                Column(name="wr_returning_hdemo_sk", typ="integer"),
                Column(name="wr_reversed_charge", typ="numeric"),
                Column(name="wr_web_page_sk", typ="integer"),
            ],
            primary_key=["wr_item_sk", "wr_order_number"],
        ),
        TableSchema(
            "web_sales",
            [
                Column(name="ws_bill_addr_sk", typ="integer"),
                Column(name="ws_bill_cdemo_sk", typ="integer"),
                Column(name="ws_bill_customer_sk", typ="integer"),
                Column(name="ws_bill_hdemo_sk", typ="integer"),
                Column(name="ws_coupon_amt", typ="numeric"),
                Column(name="ws_ext_discount_amt", typ="numeric"),
                Column(name="ws_ext_list_price", typ="numeric"),
                Column(name="ws_ext_sales_price", typ="numeric"),
                Column(name="ws_ext_ship_cost", typ="numeric"),
                Column(name="ws_ext_tax", typ="numeric"),
                Column(name="ws_ext_wholesale_cost", typ="numeric"),
                Column(name="ws_item_sk", typ="integer"),
                Column(name="ws_list_price", typ="numeric"),
                Column(name="ws_net_paid", typ="numeric"),
                Column(name="ws_net_paid_inc_ship", typ="numeric"),
                Column(name="ws_net_paid_inc_ship_tax", typ="numeric"),
                Column(name="ws_net_paid_inc_tax", typ="numeric"),
                Column(name="ws_net_profit", typ="numeric"),
                Column(name="ws_order_number", typ="integer"),
                Column(name="ws_promo_sk", typ="integer"),
                Column(name="ws_quantity", typ="integer"),
                Column(name="ws_sales_price", typ="numeric"),
                Column(name="ws_ship_addr_sk", typ="integer"),
                Column(name="ws_ship_cdemo_sk", typ="integer"),
                Column(name="ws_ship_customer_sk", typ="integer"),
                Column(name="ws_ship_date_sk", typ="integer"),
                Column(name="ws_ship_hdemo_sk", typ="integer"),
                Column(name="ws_ship_mode_sk", typ="integer"),
                Column(name="ws_sold_date_sk", typ="integer"),
                Column(name="ws_sold_time_sk", typ="integer"),
                Column(name="ws_warehouse_sk", typ="integer"),
                Column(name="ws_web_page_sk", typ="integer"),
                Column(name="ws_web_site_sk", typ="integer"),
                Column(name="ws_wholesale_cost", typ="numeric"),
            ],
            primary_key=["ws_item_sk", "ws_order_number"],
        ),
        TableSchema(
            "web_site",
            [
                Column(name="web_city", typ="character varying"),
                Column(name="web_class", typ="character varying"),
                Column(name="web_close_date_sk", typ="integer"),
                Column(name="web_company_id", typ="integer"),
                Column(name="web_company_name", typ="character"),
                Column(name="web_country", typ="character varying"),
                Column(name="web_county", typ="character varying"),
                Column(name="web_gmt_offset", typ="numeric"),
                Column(name="web_manager", typ="character varying"),
                Column(name="web_market_manager", typ="character varying"),
                Column(name="web_mkt_class", typ="character varying"),
                Column(name="web_mkt_desc", typ="character varying"),
                Column(name="web_mkt_id", typ="integer"),
                Column(name="web_name", typ="character varying"),
                Column(name="web_open_date_sk", typ="integer"),
                Column(name="web_rec_end_date", typ="date"),
                Column(name="web_rec_start_date", typ="date"),
                Column(name="web_site_id", typ="character"),
                Column(name="web_site_sk", typ="integer"),
                Column(name="web_state", typ="character"),
                Column(name="web_street_name", typ="character varying"),
                Column(name="web_street_number", typ="character"),
                Column(name="web_street_type", typ="character"),
                Column(name="web_suite_number", typ="character"),
                Column(name="web_tax_percentage", typ="numeric"),
                Column(name="web_zip", typ="character"),
            ],
            primary_key="web_site_sk",
        ),
    ],
    index_count=24,
    indexes=[],
)


# 预计算表统计信息
add_table_stats(
    dsb_schema,
    "dbgen_version",
    2,
    {"dv_create_date": 1, "dv_create_time": 1, "dv_version": 1, "dv_cmdline_args": 1},
)
add_table_stats(
    dsb_schema,
    "ship_mode",
    20,
    {"sm_ship_mode_id": 20, "sm_contract": 20, "sm_code": 4, "sm_type": 6, "sm_ship_mode_sk": 20, "sm_carrier": 20},
)
add_table_stats(
    dsb_schema,
    "reason",
    45,
    {"r_reason_sk": 45, "r_reason_desc": 44, "r_reason_id": 45},
)
add_table_stats(
    dsb_schema,
    "warehouse",
    10,
    {
        "w_city": 7,
        "w_street_type": 9,
        "w_county": 6,
        "w_zip": 10,
        "w_warehouse_name": 9,
        "w_warehouse_sk": 10,
        "w_street_name": 9,
        "w_warehouse_sq_ft": 9,
        "w_suite_number": 9,
        "w_country": 1,
        "w_warehouse_id": 10,
        "w_street_number": 9,
        "w_gmt_offset": 2,
        "w_state": 6,
    },
)
add_table_stats(
    dsb_schema,
    "store",
    102,
    {
        "s_street_type": 19,
        "s_company_name": 1,
        "s_suite_number": 55,
        "s_store_id": 51,
        "s_county": 64,
        "s_manager": 76,
        "s_division_id": 1,
        "s_street_name": 84,
        "s_division_name": 1,
        "s_state": 33,
        "s_company_id": 1,
        "s_street_number": 73,
        "s_rec_end_date": 3,
        "s_store_sk": 102,
        "s_floor_space": 85,
        "s_tax_precentage": 12,
        "s_geography_class": 1,
        "s_zip": 69,
        "s_number_employees": 46,
        "s_city": 65,
        "s_closed_date_sk": 21,
        "s_market_id": 10,
        "s_market_manager": 73,
        "s_store_name": 10,
        "s_rec_start_date": 4,
        "s_country": 1,
        "s_market_desc": 82,
        "s_hours": 3,
        "s_gmt_offset": 4,
    },
)
add_table_stats(
    dsb_schema,
    "income_band",
    20,
    {"ib_lower_bound": 20, "ib_upper_bound": 20, "ib_income_band_sk": 20},
)
add_table_stats(
    dsb_schema,
    "web_site",
    42,
    {
        "web_site_id": 21,
        "web_site_sk": 42,
        "web_country": 1,
        "web_suite_number": 32,
        "web_street_type": 17,
        "web_county": 29,
        "web_name": 7,
        "web_mkt_desc": 30,
        "web_state": 22,
        "web_zip": 28,
        "web_city": 25,
        "web_mkt_class": 31,
        "web_manager": 30,
        "web_close_date_sk": 14,
        "web_open_date_sk": 21,
        "web_tax_percentage": 12,
        "web_company_id": 5,
        "web_gmt_offset": 4,
        "web_street_number": 25,
        "web_market_manager": 35,
        "web_rec_end_date": 3,
        "web_street_name": 38,
        "web_rec_start_date": 4,
        "web_company_name": 5,
        "web_class": 1,
        "web_mkt_id": 5,
    },
)
add_table_stats(
    dsb_schema,
    "call_center",
    24,
    {
        "cc_street_number": 12,
        "cc_street_type": 10,
        "cc_call_center_id": 12,
        "cc_tax_percentage": 10,
        "cc_state": 8,
        "cc_mkt_id": 5,
        "cc_manager": 16,
        "cc_mkt_class": 20,
        "cc_division_name": 6,
        "cc_street_name": 12,
        "cc_county": 9,
        "cc_rec_start_date": 4,
        "cc_closed_date_sk": 0,
        "cc_company_name": 5,
        "cc_rec_end_date": 3,
        "cc_zip": 12,
        "cc_country": 1,
        "cc_sq_ft": 18,
        "cc_hours": 3,
        "cc_employees": 19,
        "cc_open_date_sk": 12,
        "cc_market_manager": 19,
        "cc_call_center_sk": 24,
        "cc_company": 6,
        "cc_class": 3,
        "cc_city": 10,
        "cc_division": 6,
        "cc_name": 12,
        "cc_mkt_desc": 17,
        "cc_suite_number": 12,
        "cc_gmt_offset": 2,
    },
)
add_table_stats(
    dsb_schema,
    "promotion",
    500,
    {
        "p_channel_event": 2,
        "p_discount_active": 2,
        "p_channel_radio": 2,
        "p_start_date_sk": 340,
        "p_cost": 1,
        "p_promo_id": 500,
        "p_channel_dmail": 2,
        "p_channel_demo": 2,
        "p_channel_press": 2,
        "p_channel_email": 2,
        "p_purpose": 1,
        "p_promo_sk": 500,
        "p_promo_name": 10,
        "p_channel_details": 497,
        "p_end_date_sk": 363,
        "p_channel_catalog": 2,
        "p_item_sk": 486,
        "p_channel_tv": 2,
        "p_response_target": 1,
    },
)
add_table_stats(
    dsb_schema,
    "web_page",
    200,
    {
        "wp_char_count": 151,
        "wp_web_page_sk": 200,
        "wp_creation_date_sk": 18,
        "wp_type": 7,
        "wp_link_count": 22,
        "wp_web_page_id": 101,
        "wp_url": 1,
        "wp_max_ad_count": 5,
        "wp_rec_end_date": 3,
        "wp_rec_start_date": 4,
        "wp_image_count": 7,
        "wp_autogen_flag": 2,
        "wp_customer_sk": 44,
        "wp_access_date_sk": 81,
    },
)
add_table_stats(
    dsb_schema,
    "household_demographics",
    7200,
    {"hd_vehicle_count": 6, "hd_income_band_sk": 20, "hd_dep_count": 10, "hd_demo_sk": 7200, "hd_buy_potential": 6},
)
add_table_stats(
    dsb_schema,
    "date_dim",
    73049,
    {
        "d_current_month": 2,
        "d_current_quarter": 2,
        "d_date": 73049,
        "d_day_name": 7,
        "d_year": 201,
        "d_qoy": 4,
        "d_quarter_name": 801,
        "d_date_id": 73049,
        "d_moy": 12,
        "d_holiday": 2,
        "d_following_holiday": 2,
        "d_fy_week_seq": 10436,
        "d_month_seq": 2401,
        "d_current_day": 1,
        "d_same_day_lq": 72698,
        "d_first_dom": 2401,
        "d_last_dom": 2401,
        "d_dom": 31,
        "d_fy_quarter_seq": 801,
        "d_weekend": 2,
        "d_fy_year": 201,
        "d_same_day_ly": 73000,
        "d_dow": 7,
        "d_date_sk": 73049,
        "d_quarter_seq": 801,
        "d_current_year": 2,
        "d_current_week": 1,
        "d_week_seq": 10436,
    },
)
add_table_stats(
    dsb_schema,
    "item",
    102000,
    {
        "i_category_id": 10,
        "i_rec_start_date": 4,
        "i_class": 99,
        "i_size": 7,
        "i_item_sk": 102000,
        "i_manufact_id": 999,
        "i_container": 1,
        "i_item_desc": 75171,
        "i_class_id": 17,
        "i_brand_id": 953,
        "i_rec_end_date": 3,
        "i_manager_id": 100,
        "i_product_name": 101751,
        "i_manufact": 999,
        "i_current_price": 7053,
        "i_units": 21,
        "i_item_id": 51000,
        "i_formulation": 76590,
        "i_wholesale_cost": 5036,
        "i_color": 92,
        "i_category": 10,
        "i_brand": 712,
    },
)
add_table_stats(
    dsb_schema,
    "customer_address",
    250000,
    {
        "ca_city": 986,
        "ca_country": 1,
        "ca_address_id": 250000,
        "ca_gmt_offset": 6,
        "ca_street_name": 8122,
        "ca_suite_number": 75,
        "ca_zip": 9376,
        "ca_address_sk": 250000,
        "ca_county": 1846,
        "ca_state": 51,
        "ca_location_type": 3,
        "ca_street_type": 20,
        "ca_street_number": 1000,
    },
)
add_table_stats(
    dsb_schema,
    "time_dim",
    86400,
    {
        "t_sub_shift": 4,
        "t_time_id": 86400,
        "t_time": 86400,
        "t_shift": 3,
        "t_meal_time": 3,
        "t_hour": 24,
        "t_time_sk": 86400,
        "t_second": 60,
        "t_am_pm": 2,
        "t_minute": 60,
    },
)
add_table_stats(
    dsb_schema,
    "customer",
    500000,
    {
        "c_birth_year": 69,
        "c_customer_id": 500000,
        "c_customer_sk": 500000,
        "c_login": 0,
        "c_salutation": 6,
        "c_last_name": 5000,
        "c_first_shipto_date_sk": 3651,
        "c_last_review_date_sk": 366,
        "c_birth_month": 12,
        "c_first_sales_date_sk": 3651,
        "c_current_cdemo_sk": 350105,
        "c_preferred_cust_flag": 2,
        "c_first_name": 5106,
        "c_birth_day": 31,
        "c_current_addr_sk": 196357,
        "c_birth_country": 212,
        "c_current_hdemo_sk": 7200,
        "c_email_address": 482338,
    },
)
add_table_stats(
    dsb_schema,
    "customer_demographics",
    1920800,
    {
        "cd_dep_college_count": 7,
        "cd_demo_sk": 1920800,
        "cd_purchase_estimate": 20,
        "cd_marital_status": 5,
        "cd_dep_count": 7,
        "cd_gender": 2,
        "cd_education_status": 7,
        "cd_credit_rating": 4,
        "cd_dep_employed_count": 7,
    },
)
add_table_stats(
    dsb_schema,
    "web_returns",
    1440354,
    {
        "wr_refunded_customer_sk": 430350,
        "wr_return_amt": 176711,
        "wr_return_ship_cost": 157670,
        "wr_returned_date_sk": 2474,
        "wr_return_tax": 60194,
        "wr_returning_hdemo_sk": 7181,
        "wr_web_page_sk": 110,
        "wr_refunded_addr_sk": 240751,
        "wr_returning_addr_sk": 240797,
        "wr_refunded_cdemo_sk": 549498,
        "wr_return_amt_inc_tax": 352455,
        "wr_reason_sk": 45,
        "wr_net_loss": 284653,
        "wr_refunded_hdemo_sk": 7180,
        "wr_item_sk": 101151,
        "wr_fee": 9951,
        "wr_order_number": 551449,
        "wr_returned_time_sk": 86232,
        "wr_return_quantity": 100,
        "wr_returning_cdemo_sk": 549670,
        "wr_reversed_charge": 187185,
        "wr_refunded_cash": 258967,
        "wr_account_credit": 185203,
        "wr_returning_customer_sk": 430367,
    },
)
add_table_stats(
    dsb_schema,
    "catalog_returns",
    2158260,
    {
        "cr_refunded_customer_sk": 384408,
        "cr_refunded_addr_sk": 236918,
        "cr_returned_time_sk": 86384,
        "cr_refunded_cdemo_sk": 504727,
        "cr_order_number": 1178724,
        "cr_return_ship_cost": 166103,
        "cr_reason_sk": 45,
        "cr_return_amount": 190203,
        "cr_return_quantity": 100,
        "cr_fee": 9951,
        "cr_reversed_charge": 205418,
        "cr_returning_hdemo_sk": 7194,
        "cr_catalog_page_sk": 7879,
        "cr_returning_customer_sk": 471081,
        "cr_warehouse_sk": 10,
        "cr_refunded_hdemo_sk": 7177,
        "cr_return_amt_inc_tax": 392041,
        "cr_return_tax": 60292,
        "cr_call_center_sk": 17,
        "cr_refunded_cash": 284435,
        "cr_returning_addr_sk": 247383,
        "cr_returning_cdemo_sk": 680766,
        "cr_store_credit": 203298,
        "cr_item_sk": 101883,
        "cr_net_loss": 312780,
        "cr_returned_date_sk": 2391,
        "cr_ship_mode_sk": 20,
    },
)
add_table_stats(
    dsb_schema,
    "web_sales",
    7197566,
    {
        "ws_ext_sales_price": 274570,
        "ws_bill_hdemo_sk": 7127,
        "ws_promo_sk": 500,
        "ws_ext_ship_cost": 266869,
        "ws_bill_customer_sk": 294720,
        "ws_list_price": 397,
        "ws_net_paid": 497533,
        "ws_ext_discount_amt": 269099,
        "ws_net_profit": 660558,
        "ws_ship_customer_sk": 321475,
        "ws_sales_price": 5512,
        "ws_coupon_amt": 377507,
        "ws_bill_addr_sk": 207571,
        "ws_net_paid_inc_tax": 896041,
        "ws_ship_cdemo_sk": 338461,
        "ws_web_page_sk": 110,
        "ws_quantity": 100,
        "ws_ext_wholesale_cost": 1999,
        "ws_net_paid_inc_ship": 953388,
        "ws_wholesale_cost": 20,
        "ws_bill_cdemo_sk": 339163,
        "ws_order_number": 600000,
        "ws_ship_addr_sk": 207761,
        "ws_item_sk": 102000,
        "ws_ship_mode_sk": 20,
        "ws_sold_date_sk": 2135,
        "ws_ship_date_sk": 2254,
        "ws_ext_tax": 115228,
        "ws_ext_list_price": 37576,
        "ws_sold_time_sk": 84505,
        "ws_warehouse_sk": 10,
        "ws_net_paid_inc_ship_tax": 1421020,
        "ws_ship_hdemo_sk": 7118,
        "ws_web_site_sk": 23,
    },
)
add_table_stats(
    dsb_schema,
    "inventory",
    133110000,
    {"inv_item_sk": 102000, "inv_date_sk": 261, "inv_quantity_on_hand": 1001, "inv_warehouse_sk": 10},
)
add_table_stats(
    dsb_schema,
    "catalog_sales",
    14397492,
    {
        "cs_net_profit": 781299,
        "cs_ship_customer_sk": 435251,
        "cs_bill_addr_sk": 244017,
        "cs_ship_mode_sk": 20,
        "cs_ext_ship_cost": 270939,
        "cs_ship_addr_sk": 243987,
        "cs_net_paid_inc_tax": 951455,
        "cs_item_sk": 102000,
        "cs_list_price": 397,
        "cs_wholesale_cost": 20,
        "cs_promo_sk": 500,
        "cs_quantity": 100,
        "cs_catalog_page_sk": 7881,
        "cs_order_number": 1600000,
        "cs_coupon_amt": 460059,
        "cs_ext_wholesale_cost": 1999,
        "cs_net_paid_inc_ship_tax": 1566128,
        "cs_sold_date_sk": 2138,
        "cs_net_paid_inc_ship": 1031045,
        "cs_ship_cdemo_sk": 595636,
        "cs_net_paid": 558102,
        "cs_sales_price": 5512,
        "cs_call_center_sk": 17,
        "cs_bill_hdemo_sk": 7185,
        "cs_sold_time_sk": 86316,
        "cs_ext_discount_amt": 277513,
        "cs_ext_sales_price": 281020,
        "cs_ext_list_price": 37577,
        "cs_ext_tax": 114973,
        "cs_bill_customer_sk": 422849,
        "cs_warehouse_sk": 10,
        "cs_ship_hdemo_sk": 7179,
        "cs_ship_date_sk": 2226,
        "cs_bill_cdemo_sk": 595555,
    },
)
add_table_stats(
    dsb_schema,
    "store_returns",
    7198194,
    {
        "sr_fee": 9951,
        "sr_addr_sk": 249996,
        "sr_reason_sk": 45,
        "sr_customer_sk": 494448,
        "sr_store_sk": 51,
        "sr_store_credit": 346202,
        "sr_return_time_sk": 32401,
        "sr_net_loss": 508981,
        "sr_ticket_number": 2301275,
        "sr_cdemo_sk": 1076721,
        "sr_item_sk": 102000,
        "sr_hdemo_sk": 7200,
        "sr_return_tax": 84983,
        "sr_refunded_cash": 477051,
        "sr_return_amt_inc_tax": 635721,
        "sr_return_ship_cost": 231382,
        "sr_return_quantity": 100,
        "sr_return_amt": 245793,
        "sr_returned_date_sk": 2244,
        "sr_reversed_charge": 350225,
    },
)
add_table_stats(
    dsb_schema,
    "store_sales",
    28800991,
    {
        "ss_item_sk": 102000,
        "ss_sold_date_sk": 2068,
        "ss_promo_sk": 500,
        "ss_sales_price": 5512,
        "ss_addr_sk": 248335,
        "ss_wholesale_cost": 20,
        "ss_hdemo_sk": 7193,
        "ss_net_paid": 696367,
        "ss_customer_sk": 463224,
        "ss_net_profit": 993411,
        "ss_ticket_number": 2400000,
        "ss_coupon_amt": 629508,
        "ss_net_paid_inc_tax": 1136892,
        "ss_quantity": 100,
        "ss_store_sk": 30,
        "ss_ext_sales_price": 287447,
        "ss_ext_list_price": 37577,
        "ss_ext_wholesale_cost": 1999,
        "ss_ext_tax": 129128,
        "ss_ext_discount_amt": 629508,
        "ss_sold_time_sk": 46800,
        "ss_cdemo_sk": 721988,
        "ss_list_price": 397,
    },
)
add_table_stats(
    dsb_schema,
    "catalog_page",
    12000,
    {
        "cp_end_date_sk": 97,
        "cp_catalog_number": 109,
        "cp_description": 11889,
        "cp_department": 1,
        "cp_catalog_page_id": 12000,
        "cp_type": 3,
        "cp_catalog_page_number": 111,
        "cp_start_date_sk": 91,
        "cp_catalog_page_sk": 12000,
    },
)
