from .schema import Column, DatabaseSchema, TableSchema


hockey_schema = DatabaseSchema(
    "hockey",
    table_count=22,
    tables=[
        TableSchema(
            "abbrev",
            [
                Column(name="code", typ="character varying"),
                Column(name="fullname", typ="character varying"),
                Column(name="type", typ="character varying"),
            ],
            primary_key=["type", "code"],
        ),
        TableSchema(
            "awardscoaches",
            [
                Column(name="award", typ="character varying"),
                Column(name="coachid", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="note", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
        ),
        TableSchema(
            "awardsmisc",
            [
                Column(name="award", typ="character varying"),
                Column(name="id", typ="character varying"),
                Column(name="lgid", typ="character varying"),
                Column(name="name", typ="character varying"),
                Column(name="note", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
            primary_key="name",
        ),
        TableSchema(
            "awardsplayers",
            [
                Column(name="award", typ="character varying"),
                Column(name="lgid", typ="character varying"),
                Column(name="note", typ="character varying"),
                Column(name="playerid", typ="integer"),
                Column(name="pos", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
            primary_key=["playerid", "award", "year"],
        ),
        TableSchema(
            "coaches",
            [
                Column(name="c_id", typ="integer"),
                Column(name="coachid", typ="character varying"),
                Column(name="g", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="notes", typ="character varying"),
                Column(name="postg", typ="character varying"),
                Column(name="postl", typ="character varying"),
                Column(name="postt", typ="character varying"),
                Column(name="postw", typ="character varying"),
                Column(name="stint", typ="integer"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["coachid", "year", "tmid", "stint"],
        ),
        TableSchema(
            "combinedshutouts",
            [
                Column(name="date", typ="integer"),
                Column(name="idgoalie1", typ="integer"),
                Column(name="idgoalie2", typ="integer"),
                Column(name="month", typ="integer"),
                Column(name="oppid", typ="character varying"),
                Column(name="r_p", typ="character varying"),
                Column(name="tmid", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
        ),
        TableSchema(
            "goalies",
            [
                Column(name="eng", typ="character varying"),
                Column(name="ga", typ="character varying"),
                Column(name="gp", typ="character varying"),
                Column(name="l", typ="character varying"),
                Column(name="lgid", typ="character varying"),
                Column(name="min", typ="character varying"),
                Column(name="playerid", typ="integer"),
                Column(name="posteng", typ="character varying"),
                Column(name="postga", typ="character varying"),
                Column(name="postgp", typ="character varying"),
                Column(name="postl", typ="character varying"),
                Column(name="postmin", typ="character varying"),
                Column(name="postsa", typ="character varying"),
                Column(name="postsho", typ="character varying"),
                Column(name="postt", typ="character varying"),
                Column(name="postw", typ="character varying"),
                Column(name="sa", typ="character varying"),
                Column(name="sho", typ="character varying"),
                Column(name="stint", typ="integer"),
                Column(name="t_ol", typ="character varying"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="character varying"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["playerid", "year", "stint"],
        ),
        TableSchema(
            "goaliessc",
            [
                Column(name="ga", typ="integer"),
                Column(name="gp", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="min", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="sho", typ="integer"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["playerid", "year"],
        ),
        TableSchema(
            "goaliesshootout",
            [
                Column(name="ga", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="sa", typ="integer"),
                Column(name="stint", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
        ),
        TableSchema(
            "hof",
            [
                Column(name="category", typ="character varying"),
                Column(name="hofid", typ="character varying"),
                Column(name="name", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
            primary_key="hofid",
        ),
        TableSchema(
            "master",
            [
                Column(name="birthcity", typ="character varying"),
                Column(name="birthcountry", typ="character varying"),
                Column(name="birthday", typ="character varying"),
                Column(name="birthmon", typ="character varying"),
                Column(name="birthstate", typ="character varying"),
                Column(name="birthyear", typ="character varying"),
                Column(name="coachid", typ="integer"),
                Column(name="deathcity", typ="character varying"),
                Column(name="deathcountry", typ="character varying"),
                Column(name="deathday", typ="character varying"),
                Column(name="deathmon", typ="character varying"),
                Column(name="deathstate", typ="character varying"),
                Column(name="deathyear", typ="character varying"),
                Column(name="firstname", typ="character varying"),
                Column(name="firstnhl", typ="character varying"),
                Column(name="firstwha", typ="character varying"),
                Column(name="height", typ="character varying"),
                Column(name="hofid", typ="character varying"),
                Column(name="hrefid", typ="character varying"),
                Column(name="ihdbid", typ="character varying"),
                Column(name="lastname", typ="character varying"),
                Column(name="lastnhl", typ="character varying"),
                Column(name="lastwha", typ="character varying"),
                Column(name="legendsid", typ="character varying"),
                Column(name="namegiven", typ="character varying"),
                Column(name="namenick", typ="character varying"),
                Column(name="namenote", typ="character varying"),
                Column(name="p_id", typ="integer"),
                Column(name="playerid", typ="character varying"),
                Column(name="pos", typ="character varying"),
                Column(name="shootcatch", typ="character varying"),
                Column(name="weight", typ="character varying"),
            ],
        ),
        TableSchema(
            "scoring",
            [
                Column(name="a", typ="integer"),
                Column(name="g", typ="integer"),
                Column(name="gp", typ="integer"),
                Column(name="gtg", typ="character varying"),
                Column(name="gwg", typ="character varying"),
                Column(name="lgid", typ="character varying"),
                Column(name="pim", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="plus_minus", typ="character varying"),
                Column(name="pos", typ="character varying"),
                Column(name="post_pm", typ="character varying"),
                Column(name="posta", typ="character varying"),
                Column(name="postg", typ="character varying"),
                Column(name="postgp", typ="character varying"),
                Column(name="postgwg", typ="character varying"),
                Column(name="postpim", typ="character varying"),
                Column(name="postppa", typ="character varying"),
                Column(name="postppg", typ="character varying"),
                Column(name="postpts", typ="character varying"),
                Column(name="postsha", typ="character varying"),
                Column(name="postshg", typ="character varying"),
                Column(name="postsog", typ="character varying"),
                Column(name="ppa", typ="character varying"),
                Column(name="ppg", typ="character varying"),
                Column(name="pts", typ="integer"),
                Column(name="sha", typ="character varying"),
                Column(name="shg", typ="character varying"),
                Column(name="sog", typ="character varying"),
                Column(name="stint", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
        ),
        TableSchema(
            "scoringsc",
            [
                Column(name="a", typ="integer"),
                Column(name="g", typ="integer"),
                Column(name="gp", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="pim", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="pos", typ="character varying"),
                Column(name="pts", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
        ),
        TableSchema(
            "scoringshootout",
            [
                Column(name="g", typ="integer"),
                Column(name="gdg", typ="integer"),
                Column(name="playerid", typ="integer"),
                Column(name="s", typ="integer"),
                Column(name="stint", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
        ),
        TableSchema(
            "scoringsup",
            [
                Column(name="playerid", typ="integer"),
                Column(name="ppa", typ="character varying"),
                Column(name="sha", typ="character varying"),
                Column(name="year", typ="integer"),
            ],
        ),
        TableSchema(
            "seriespost",
            [
                Column(name="goalsloser", typ="integer"),
                Column(name="goalswinner", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgidloser", typ="character varying"),
                Column(name="lgidwinner", typ="character varying"),
                Column(name="note", typ="character varying"),
                Column(name="round", typ="character varying"),
                Column(name="series", typ="character varying"),
                Column(name="t", typ="integer"),
                Column(name="tmidloser", typ="character varying"),
                Column(name="tmidwinner", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmidloser", typ="integer"),
                Column(name="year_tmidwinner", typ="integer"),
            ],
        ),
        TableSchema(
            "teams",
            [
                Column(name="benchminor", typ="character varying"),
                Column(name="confid", typ="character varying"),
                Column(name="divid", typ="character varying"),
                Column(name="franchid", typ="character varying"),
                Column(name="g", typ="integer"),
                Column(name="ga", typ="integer"),
                Column(name="gf", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="name", typ="character varying"),
                Column(name="otl", typ="character varying"),
                Column(name="pim", typ="character varying"),
                Column(name="pk_id", typ="integer"),
                Column(name="pkc", typ="character varying"),
                Column(name="pkg", typ="character varying"),
                Column(name="playoff", typ="character varying"),
                Column(name="ppc", typ="character varying"),
                Column(name="ppg", typ="character varying"),
                Column(name="pts", typ="integer"),
                Column(name="rank1", typ="integer"),
                Column(name="sha", typ="character varying"),
                Column(name="shf", typ="character varying"),
                Column(name="sol", typ="character varying"),
                Column(name="sow", typ="character varying"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
            ],
            primary_key="pk_id",
        ),
        TableSchema(
            "teamshalf",
            [
                Column(name="g", typ="integer"),
                Column(name="ga", typ="integer"),
                Column(name="gf", typ="integer"),
                Column(name="half", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="rank1", typ="integer"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["year", "tmid", "half"],
        ),
        TableSchema(
            "teamsplits",
            [
                Column(name="aprl", typ="character varying"),
                Column(name="aprol", typ="character varying"),
                Column(name="aprt", typ="character varying"),
                Column(name="aprw", typ="character varying"),
                Column(name="decl", typ="character varying"),
                Column(name="decol", typ="character varying"),
                Column(name="dect", typ="character varying"),
                Column(name="decw", typ="character varying"),
                Column(name="febl", typ="integer"),
                Column(name="febol", typ="character varying"),
                Column(name="febt", typ="integer"),
                Column(name="febw", typ="integer"),
                Column(name="hl", typ="integer"),
                Column(name="hotl", typ="character varying"),
                Column(name="ht", typ="integer"),
                Column(name="hw", typ="integer"),
                Column(name="janl", typ="integer"),
                Column(name="janol", typ="character varying"),
                Column(name="jant", typ="integer"),
                Column(name="janw", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="marl", typ="character varying"),
                Column(name="marol", typ="character varying"),
                Column(name="mart", typ="character varying"),
                Column(name="marw", typ="character varying"),
                Column(name="novl", typ="character varying"),
                Column(name="novol", typ="character varying"),
                Column(name="novt", typ="character varying"),
                Column(name="novw", typ="character varying"),
                Column(name="octl", typ="character varying"),
                Column(name="octol", typ="character varying"),
                Column(name="octt", typ="character varying"),
                Column(name="octw", typ="character varying"),
                Column(name="rl", typ="integer"),
                Column(name="rotl", typ="character varying"),
                Column(name="rt", typ="integer"),
                Column(name="rw", typ="integer"),
                Column(name="sepl", typ="character varying"),
                Column(name="sepol", typ="character varying"),
                Column(name="sept", typ="character varying"),
                Column(name="sepw", typ="character varying"),
                Column(name="tmid", typ="character varying"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["year", "tmid"],
        ),
        TableSchema(
            "teamspost",
            [
                Column(name="benchminor", typ="character varying"),
                Column(name="g", typ="integer"),
                Column(name="ga", typ="integer"),
                Column(name="gf", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="pim", typ="character varying"),
                Column(name="pkc", typ="character varying"),
                Column(name="pkg", typ="character varying"),
                Column(name="ppc", typ="character varying"),
                Column(name="ppg", typ="character varying"),
                Column(name="sha", typ="character varying"),
                Column(name="shf", typ="character varying"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["year", "tmid"],
        ),
        TableSchema(
            "teamssc",
            [
                Column(name="g", typ="integer"),
                Column(name="ga", typ="integer"),
                Column(name="gf", typ="integer"),
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="pim", typ="character varying"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["year", "tmid"],
        ),
        TableSchema(
            "teamvsteam",
            [
                Column(name="l", typ="integer"),
                Column(name="lgid", typ="character varying"),
                Column(name="oppid", typ="character varying"),
                Column(name="otl", typ="character varying"),
                Column(name="t", typ="integer"),
                Column(name="tmid", typ="character varying"),
                Column(name="w", typ="integer"),
                Column(name="year", typ="integer"),
                Column(name="year_oppid", typ="integer"),
                Column(name="year_tmid", typ="integer"),
            ],
            primary_key=["year", "tmid", "oppid"],
        ),
    ],
    index_count=13,
    indexes=[],
)
