from .schema import Column, DatabaseSchema, TableSchema


ssb_schema = DatabaseSchema(
    "ssb",
    table_count=5,
    tables=[
        TableSchema(
            "customer",
            [
                Column(name="c_address", typ="character varying"),
                Column(name="c_city", typ="character varying"),
                Column(name="c_custkey", typ="integer"),
                Column(name="c_mktsegment", typ="character varying"),
                Column(name="c_name", typ="character varying"),
                Column(name="c_nation", typ="character varying"),
                Column(name="c_phone", typ="character varying"),
                Column(name="c_region", typ="character varying"),
            ],
            primary_key="c_custkey",
        ),
        TableSchema(
            "dim_date",
            [
                Column(name="d_date", typ="character varying"),
                Column(name="d_datekey", typ="integer"),
                Column(name="d_daynuminmonth", typ="integer"),
                Column(name="d_daynuminweek", typ="integer"),
                Column(name="d_daynuminyear", typ="integer"),
                Column(name="d_dayofweek", typ="character varying"),
                Column(name="d_holidayfl", typ="integer"),
                Column(name="d_lastdayinmonthfl", typ="integer"),
                Column(name="d_lastdayinweekfl", typ="integer"),
                Column(name="d_month", typ="character varying"),
                Column(name="d_monthnuminyear", typ="integer"),
                Column(name="d_sellingseason", typ="character varying"),
                Column(name="d_weekdayfl", typ="integer"),
                Column(name="d_weeknuminyear", typ="integer"),
                Column(name="d_year", typ="integer"),
                Column(name="d_yearmonth", typ="character varying"),
                Column(name="d_yearmonthnum", typ="integer"),
            ],
            primary_key="d_datekey",
        ),
        TableSchema(
            "lineorder",
            [
                Column(name="lo_commitdate", typ="integer"),
                Column(name="lo_custkey", typ="integer"),
                Column(name="lo_discount", typ="integer"),
                Column(name="lo_extendedprice", typ="integer"),
                Column(name="lo_linenumber", typ="bigint"),
                Column(name="lo_orderdate", typ="integer"),
                Column(name="lo_orderkey", typ="bigint"),
                Column(name="lo_orderpriority", typ="character varying"),
                Column(name="lo_ordertotalprice", typ="integer"),
                Column(name="lo_partkey", typ="integer"),
                Column(name="lo_quantity", typ="integer"),
                Column(name="lo_revenue", typ="integer"),
                Column(name="lo_shipmode", typ="character varying"),
                Column(name="lo_shippriority", typ="integer"),
                Column(name="lo_suppkey", typ="integer"),
                Column(name="lo_supplycost", typ="integer"),
                Column(name="lo_tax", typ="integer"),
            ],
        ),
        TableSchema(
            "part",
            [
                Column(name="p_brand1", typ="character varying"),
                Column(name="p_category", typ="character varying"),
                Column(name="p_color", typ="character varying"),
                Column(name="p_container", typ="character varying"),
                Column(name="p_mfgr", typ="character varying"),
                Column(name="p_name", typ="character varying"),
                Column(name="p_partkey", typ="integer"),
                Column(name="p_size", typ="integer"),
                Column(name="p_type", typ="character varying"),
            ],
            primary_key="p_partkey",
        ),
        TableSchema(
            "supplier",
            [
                Column(name="s_address", typ="character varying"),
                Column(name="s_city", typ="character varying"),
                Column(name="s_name", typ="character varying"),
                Column(name="s_nation", typ="character varying"),
                Column(name="s_phone", typ="character varying"),
                Column(name="s_region", typ="character varying"),
                Column(name="s_suppkey", typ="integer"),
            ],
            primary_key="s_suppkey",
        ),
    ],
    index_count=4,
    indexes=[],
)
